### ISSUE TITLE
absREL Vision not loading JSON file

### ISSUE THREAD

**Issue by carterjosh** [veg/hyphy-vision#24]
Hello,

I am attempting to visualize the output of absREL but when I load my file to the web page nothing changes. I have tried both Chrome and Safari. Please let me know if I there is anything I else I can try.

Thanks,
Josh

**Comment by stevenweaver** [comment]
Hello, 

Sorry for missing this issue. I was out on holiday on Nov. 11th, and I must have missed this notification. 

Can you please send me the JSON output you are trying to load at sweaver@temple.edu? It is most likely that the JSON that HyPhy output is missing a key that is expected.

**Comment by mht85** [comment]
Hi,

I'm having the same problem as well with loading my JSON output to the web page. May I know what the solution for this was?

Thanks,
Mun

**Comment by schraderL** [comment]
I have the same for absREL and BUSTED. So far, I tried Firefox and Safari, without success.

**Comment by stevenweaver** [comment]
Dear Mun and Lukas,

This was an bug that was re-introduced with the latest push. We are investigating the issue now.

Best,
Steven

**Comment by stephenshank** [comment]
Dear @carterjosh, @mht85 and @schraderL,

Just wanted to give an update... the current [HyPhy Vision](vision.hyphy.org) should be compatible with JSON output from HyPhy version 2.3.4 and above. Please let me know if you run into any issues.

Best,
Stephen

**Comment by cybokat** [comment]
3/30/2018 HYPHY Vision is not loading .json output generated with HYPHY V2.7.7. Is there a way to re-write the V2.7.7 .json so it aligns with the output from V2.3.4 and can be visualized?
Thank you

**Comment by spond** [comment]
Dear @cybokat,

There is no version 2.7.7, so I presume you are referring to 2.2.7? The way to deal with this issue is to use **older** hyphy-vision versions. Take a look at https://github.com/veg/hyphy-vision/releases for a list of historical version. 2.2.7 was a version from 2016, so you might want to download and install a contemporaneous version of hyphy-vision. Since hyphy-vision is a JavaScript app, you should be able to build it and open it in any modern browser on your local machine.

@stephenshank, could you please see how hard it is to create a page of "legacy" viewers? 

Best,
Sergei
